name: 01-Hello World

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting messages
        run: echo "Hello, GitHub Actions!"
      
      - name: Print Default GH Action variables
        run: |
          echo "This step is to run series of shell commands."
          echo "GitHub Runner OS flavour is: $RUNNER_OS"
          echo "The repository is: $GITHUB_REPOSITORY"
          echo "The workflow running on the path: $PWD"
          echo "Event name: $GITHUB_EVENT_NAME"
          echo "Branch ref: $GITHUB_REF"
          echo "Commit SHA: $GITHUB_SHA"
          echo "Pushed by: $GITHUB_REF"
