name: Argo CD deployment on EKS clsuter in AWS
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      INIT_SCRIPT_REPO: https://raw.githubusercontent.com/thangacodes/terraform_usecases/main/init_script_for_terraform.sh
      SCRIPT_FILE: init_script_for_terraform.sh
    steps:
    - name: CheckOut
      uses: actions/checkout@v3
    - name: Navigate to the Terraform scripts directory
      run: |
        echo "List Out the files in Current directory: $(pwd)"
        cd terra-codes/argocd
        ls -al
        echo "sleep for '3' seconds"
        sleep 3
        echo "download terraform inti script from other repository"
        wget -O ${{ env.SCRIPT_FILE }} ${{ env.INIT_SCRIPT_REPO }} && \
        chmod +x ${{ env.SCRIPT_FILE }}
        # ./${{ env.SCRIPT_FILE }}
        ls -al
        sleep 5
    - name: Workspace CleanUp
      run: |
        echo "Cleaning up workspace..."
        rm -rf *
        echo "Listing contents after Workspace cleaned up.."
        ls -al $(pwd)
