name: Argo CD deployment on EKS clsuter in AWS
# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Navigate to the Terraform scripts directory
      run: |
        echo "List Out the files in Current directory: $(pwd)"
        cd terra-codes/argocd
        ls -al
        echo "sleep for '3' seconds"
        sleep 3
        echo "download terraform inti script from other repository"
        wget -O init_script_for_terraform.sh https://raw.githubusercontent.com/thangacodes/terraform_usecases/main/init_script_for_terraform.sh && \
        chmod +x init_script_for_terraform.sh
        # ./init_script_for_terraform.sh
        ls -al
        sleep 5
    - name: cleanup
      run: |
        echo "Cleaning up workspace..."
        rm -rf *
        echo "Workspace cleaned. Listing contents to confirm:"
        ls -al
