name: Multi-Env CI/CD
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment (dev, stage, prod)'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - stage
          - prod
      change_number:
        description: 'Change number'
        type: string
        required: true
        default: 'CHGXXXXX'
      session_name:
        description: 'AWS Session Name'
        type: string
        required: true
        default: 'OIDC'
      script_path:
        description: 'Path for terraform and Shell Scripts'
        required: true
        default: 'terra-codes/eks-tf'
        type: choice
        options:
          - terra-codes/tflint_tf
          - terra-codes/scripts/stage
          - terra-codes/scripts/prod
env:
  TERRAFORM_VERSION: "1.10.5"
permissions:
  id-token: write
  contents: read
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ vars.AWS_REGION }}
      ROLE_TO_ASSUME: ${{ secrets.IAM_ROLE_TO_ASSUME }}
      SESSION_NAME: ${{ inputs.session_name }}
      SCRIPT_PATH:  ${{ inputs.script_path }}
    steps:
      - name: "Checking input values given by an user"
        run: |
          echo "User entered the change number is: ${{ inputs.change_number }}"
          echo "AWS session name is: ${{ inputs.session_name }}"
          echo "User entered tf code path is: ${{ inputs.script_path }}"
      - name: Checkout code
        uses: actions/checkout@v3
      - name: "Configure AWS Credentials via OIDC"
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.IAM_ROLE_TO_ASSUME }}
          role-session-name: ${{ env.SESSION_NAME }}
          aws-region: ${{ vars.AWS_REGION }}
      - name: Setup Terraform CLI
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
      - name: Run for DEV
        if: ${{ github.event.inputs.environment == 'dev' }}
        run: |
          echo "Running DEV tasks..."
          cd ${{ env.SCRIPT_PATH }}
      - name: Run for STAGE
        if: ${{ github.event.inputs.environment == 'stage' }}
        run: |
          echo "Running STAGE tasks..."
          echo "Navigating to staging script path:" ${{ env.SCRIPT_PATH }}
          cd ${{ env.SCRIPT_PATH }}
          ls -l 
          bash stage.sh
      - name: Run for PROD
        if: ${{ github.event.inputs.environment == 'prod' }}
        run: 
          echo "Running PROD tasks..."
          echo "Navigating to staging script path:" ${{ env.SCRIPT_PATH }}
          cd ${{ env.SCRIPT_PATH }}
          ls -l 
          bash prod.sh
