name: GH to deploy python based flask application
on:
  push:
    branches:
      - main
      - dev
      - stage
  pull_request:
    branches:
      - main
      - dev
      - stage
jobs:
  flask_job:
    runs-on: ubuntu-latest
    steps:
      - name: Code Cloning
        uses: actions/checkout@v2
      - name: Get to know about the GH runner information
        run: |
          echo "Executor name is:" $(whoami)
          echo "GitHub workflow path is:" $(pwd)
          echo "GitHub hosted machine name is:" $(hostname)
      - name: Setup GitHub Action Bot
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - name: Build Flask Docker Image
        run: |
          echo "Building Docker image in: $(pwd)"
          pwd
          ls -ltr
          docker build -t flaskimage:${{ github.sha }} .
        working-directory: flaskapp






      
