name: Demo Workflow
on:
  push:
    branches:
      - main
jobs:
  example_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - name: Creating a dummy file
        run: |
          echo "Some changes" >> dummy.txt
      - name: Commit and push changes
        run: |
          git add dummy.txt
          git commit -m "workflow automated with the help of github bot"
          git push
      - name: Check GitHub Actions bot user
        run: git log -1 --oneline
