# Deploying static html on s3 bucket
name: Deploy Static to S3 Bucket
on: 
  push:
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Code from Repository
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.ARN_TO_ASSUME }}
          aws-region: ${{ vars.AWS_REGION }}
      - name: Deploy to S3 bucket for html file
        run: |
          aws s3 sync . s3://gitops-bucket2026/ \
          --exclude "*" \
          --include "static_web/simple.html"
