name: GitHub Bot
on:
  push:
    branches:
      - main
      - dev
      - stage
  pull_request:
    branches:
      - main
      - dev
      - stage
jobs:
  combine-and-commit:
    runs-on: ubuntu-latest
    env:
      GITBOT_USERNAME: github-actions[bot]
      GITBOT_USERMAIL: github-actions[bot]@users.noreply.github.com
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Configure GitHub Bot
        run: |
          git config --global user.name "${{ env.GITBOT_USERNAME }}"
          git config --global user.email "${{ env.GITBOT_USERMAIL }}"
      - name: Github Host machine information
        run: |
          echo "Your Git Hosted machine name is:" $(hostname)
          echo "Your Git Hosted machine job folder path is:" $(pwd)
          echo "Your Git Hosted machine IP Address is:" $(hostname -i)
          sleep 5
      - name: Add a new file
        run: |
          echo "This file was updated by GitHub Actions on $(date)" >> bot_output.txt
          pwd
          ls -ltr
      - name: Commit Changes
        run: |
          git add bot_output.txt
          git commit -m "Auto-update bot_output.txt on $(date)" || echo "No changes to commit"
      - name: Push Changes
        run: |
          git push origin HEAD:${{ github.ref_name }}
