name: Terraform CICD

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main
jobs:
  provision-ec2:
    name: "Terraform Lint, Security Check using TFsec, and Plan"
    runs-on: ubuntu-latest
    
    env:
      AWS_REGION: 'ap-south-1'
      TF_VERSION: '1.4.0'
      TFLINT_VERSION: '0.46.1'
      TFSEC_VERSION: '1.28.1'

    steps:
    - name: "Checkout GitHub repository"
      uses: actions/checkout@v3
  
    - name: "Configure AWS API Credentials"
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.TF_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.TF_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: "Install TFLint"
      run: |
        curl -sLo tflint.zip https://github.com/terraform-linters/tflint/releases/download/v${{ env.TFLINT_VERSION }}/tflint_linux_amd64.zip
        unzip tflint.zip -d /usr/local/bin/
        tflint --version

    - name: "Install tfsec"
      run: |
        curl -sLo tfsec https://github.com/aquasecurity/tfsec/releases/download/v${{ env.TFSEC_VERSION }}/tfsec-linux-amd64
        chmod +x tfsec
        mv tfsec /usr/local/bin/
        tfsec --version
    
    - name: "Setup Terraform"
      uses: hashicorp/setup-terraform@v2
      with: 
        terraform_version: ${{ env.TF_VERSION }}

    - name: "Terraform Init"
      run: |
        cd terra-codes
        echo "Current directory: $(pwd)"
        ls -ltr
        sleep 3
        echo "terraform init in progress"
        terraform init
        echo "terraform lint in progress"
        tflint
        echo "terraform static code analysis in progress"
        tfsec
        echo "terraform plan in progress"
        terraform plan
