name: TerraformScript
on:
  push:
  workflow_dispatch:
    inputs:
      tfaction:
        description: "Terraform Script Execution"
        required: true
        default: "Do you want to deploy in Dev?"
        type: string
jobs:
  provision-ec2:
    runs-on: ubuntu-latest
    environment: dev 
    steps:
    - name: "Check out code"
      uses: actions/checkout@v3
    - name: "Setup Node.js"
      uses: actions/setup-node@v3
      with:
        node-version: "14"
    - name: Save state
      run: echo "TFSTATE=dev.tfsate"
    - name: "Configure AWS API Credentials"
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: "${{ secrets. TF_ACCESS_KEY }}"
        aws-secret-access-key: "${{ secrets. TF_SECRET_ACCESS_KEY }}"
        aws-region: "${{ secrets.REGION }}"
        audience: sts.amazonaws.com
    - name: "Setup Terraform"
      uses: hashicorp/setup-terraform@v2
      with: 
        terraform_version: "1.3.0"
    - name: "Navigating to the terraform scripts directory"
      run: |
        echo "changing directory to terraform scripts folder"
        cd terra-codes/
        echo "list out the files in terra-codes folder"
        ls -ltr
        echo "Terraform init in progress"
        terraform init
        echo "Terraform fmt in progress"
        terraform fmt
        echo "Terraform validate in progress"
        terraform validate
        echo "Terraform plan in progress"
        terraform plan
        
